34168.3 <c-35#200> Created logger
34168.3 <c-35#200> appl_initialize was called
34168.3 <c-35#200:1> Logger was updated
34168.3 <c-35#200:1> Started intializing cube lib
34168.3 <c-35#200:1> Finished intializing cube lib with worker, starting to work
34168.3 <c-35#200:1> requestCubes => [46] Buffer size: 0
34168.3 <c-35#200:1> Sent requestCubes signal to root
34168.3 <c-35#200:1> Received 1 cubes from root
34168.3 <c-35#200:1> The main loop continues
34168.3 <c-35#200:1> Started solving a cube
34168.3 <c-35#200:1> Cube failed
34168.3 <c-35#200:1> Added failed cube
34168.3 <c-35#200:1> returnFailedCubes => [46] Buffer size: 3
34168.3 <c-35#200:1> Sent 1 failed cubes to root
34168.3 <c-35#200:1> Received receivedFailedCubes signal from root
34168.4 <c-35#200:1> requestCubes => [46] Buffer size: 0
34168.4 <c-35#200:1> Sent requestCubes signal to root
34168.4 <c-35#200:1> Received 1 cubes from root
34168.4 <c-35#200:1> The main loop continues
34168.4 <c-35#200:1> Started solving a cube
35161.1 <c-35#200:1> appl_interrupt was called
35161.1 <c-35#200:1> Interrupting worker
35161.1 <c-35#200:1> appl_interrupt was called
35161.1 <c-35#200:1> appl_withdraw was called
35161.1 <c-35#200:1> Started withdraw thread
35161.1 <c-35#200:1> STOP (0.00s since last cb)
35161.1 <c-35#200:1> Solving interrupted
35161.1 <c-35#200:1> The main loop continues
35161.1 <c-35#200:1> Leaving the main loop due to an interruption
35161.1 <c-35#200:1> Finished withdrawing lib
35161.1 <c-35#200:1> Enter destructor of CubeWorker
35161.1 <c-35#200:1> Time waiting for messages: 0.000
35161.2 <c-35#200:1> Enter destructor of CubeWorkerInterface
35161.2 <c-35#200:1> Enter destructor of CubeRoot
35161.2 <c-35#200:1> Finished withdraw thread
35224 <c-35#200:1> Enter destructor
35224 <c-35#200:1> Time working: 992.824
35224 <c-35#200:1> Time suspended: 0.000
35224 <c-35#200:1> Joined cleanup thread
35224 <c-35#200:1> Exit destructor
35224 <c-35#200:1> Destructing logger
